version: "3.8"

services:
  plex-album-auto-rater:
    build: .
    container_name: plex-album-auto-rater
    env_file:
      - .env
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=plex-album-auto-rater"
